# Copyright 2017, Juniper Networks Pvt Ltd.
# All rights reserved.
# Deploys OSPF to the topology
# command example: ansible-playbook -i all.inv deploy-ospf.yml
# Successfully ran on ansible version: ansible 2.4.2.0
---
- name: Deploy OSPF to the topology
  hosts: junos-mh-spine
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Deploy OSPF to the spine
      junos_install_config:
        host: "{{ inventory_hostname }}"
        replace: no
        overwrite: no
        confirm: 5
        file: spine.set
    - name: Confirm the commit
      junos_commit:
        host: "{{ inventory_hostname }}"
        comment: "commit confirmed"
- name: Commit
  hosts: junos-mh-leaf
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Deploy OSPF to the leaf
      junos_install_config:
        host: "{{ inventory_hostname }}"
        replace: no
        overwrite: no
        confirm: 5
        file: leaf.set
    - name: Confirm the commit
      junos_commit:
        host: "{{ inventory_hostname }}"
        comment: "commit confirmed"
