---
 - name: create golden directory
   hosts: localhost
   gather_facts: no
   tasks:

   - name: create golden directory
     file: 
       path: "{{playbook_dir}}/{{ item }}" 
       state: directory
     with_items: 
      - golden_configuration
      - golden_configuration/minimum_configuration

 - name: set and collect junos golden configuration
   hosts: junos-ssh
   connection: local
   gather_facts: no    
   tasks:

    - name: Collect configuration in text format from devices
      junos_facts:
       gather_subset: config
       config_format: text
      register: result_text

    - name: copy collected configuration in golden directory
      copy:
        content: "{{ result_text.ansible_facts.ansible_net_config }}"
        dest: "{{ playbook_dir }}/golden_configuration/minimum_configuration/{{ inventory_hostname }}.conf"
