# Copyright 2017, Juniper Networks Pvt Ltd.
# All rights reserved.
# Removes BGP from the underlay topology
# command example: ansible-playbook -i all.inv bgp-remove.yml
# Successfully ran on ansible version: ansible 2.4.2.0
---
- name: Remove BGP underlay from all devices
  hosts: junos-mh-all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Remove BGP underlay config
      junos_install_config:
        host: "{{ inventory_hostname }}"
        replace: no
        overwrite: no
        confirm: 5
        file: extinct-bgp.set
    - name: Confirm the commit
      junos_commit:
        host: "{{ inventory_hostname }}"
        comment: "commit confirmed"
