# Copyright 2017, Juniper Networks Pvt Ltd.
# All rights reserved.
# Prepares Topology for Multi-Homing 
# command example: ansible-playbook -i all.inv deploy-arch.yml
# Successfully ran on ansible version: ansible 2.4.2.0
---
- name: Removes interfaces from service to create a multihomed device
  hosts: junos-mh-device
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: push setup to device
      junos_install_config:
        host: "{{ inventory_hostname }}"
        replace: no
        overwrite: no
        confirm: 5
        file: setup-arch.set
    - name: Confirm the commit
      junos_commit:
        host: "{{ inventory_hostname }}"
        comment: "commit confirmed"
