# Copyright 2017, Juniper Networks Pvt Ltd.
# All rights reserved.
# Checks the health of the devices and verifies reachability
# command example: ansible-playbook -i all.inv junos_health_check-dual.yml
# Successfully ran on ansible version: ansible 2.4.2.0
---
- name: Get Device Facts
  hosts: junos-spine
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Retrieve information from devices running Junos OS
    junos_get_facts:
        host: "{{ inventory_hostname }}"
    register: junos

  - name: version
    debug: msg="{{ junos.facts.version }}"
- name: Get Device Facts
  hosts: junos-leaf
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Retrieve information from devices running Junos OS
    junos_get_facts:
        host: "{{ inventory_hostname }}"
    register: junos

  - name: version
    debug: msg="{{ junos.facts.version }}"
